### ISSUE TITLE
Mise en place de l'environnement de pré-production

### ISSUE THREAD

**Issue by dheavy** [dheavy/unicorn-paris#15]
Il s'agît de créer un sous-domaine type [https://next.unicorn-paris.com](https://next.unicorn-paris.com) pointant vers une installation de WP contenant, au démarrage, le code du backend. Par la suite, les avancées en frontend.

@UnicornParis, pour pouvoir avancer...
- [x] Fournir un accès FTP à un serveur accessible via un nom de domaine.
- [x] Fournir un accès à un panneau d'administration de registrar (type OVH etc...) permettant de créer des nouveaux sous-domaines.
- [x] Achat et mise à disposition de [license ACF Pro](https://www.advancedcustomfields.com/pro/).

Tu peux fournir toutes ces infos en discussion de ce ticket.

@dheavy par la suite...
- [x] Audit des possibilités et retour si éléments manquants.
- [x] Installation de Wordpress.
- [x] Installation du thème et des plugins "Unicorn Paris"
- [x] Création de comptes pour @UnicornParis 

Puis...
- [x] Création de l'environnement sur un serveur *nix pour Unicorn
- [x] Migration des contenus vers ce serveur

**Comment by UnicornParis** [comment]
### Accès Ftp : 

- ftp.cluster015.ovh.net

**Login :** `unicornp`
**Mot de passe** : `7WyKAHfP`

### Accès OVH : 
**Login :** `la135691-ovh`
**Mot de passe** : `Ul1cp0150`

@dheavy Pour la license ACF Pro on prend la _personal_ ou la _Developer_ ?

**Comment by UnicornParis** [comment]
Achat et mise à disposition de license ACF Pro :
https://www.advancedcustomfields.com/my-account/
Account : contact@unicorn-paris.com
Password : Ul1cp0150
